### ISSUE TITLE
[BUG]: Cannot get enything to work

### ISSUE THREAD

**Issue by pandosme** [naimo84/node-red-contrib-generate-password#1]
The 2 nodes keeps generate JSON error.  Looking at the code in I see that it tries to parse an object.

`
let options = JSON.parse(JSON.stringify(configOptions || {
                length: 10,
                numbers: true
}));
`

You placed the || inside the parse function.

Here is how I would do it

`
var options = JSON.parse(config.options) || {
  length: 10,
  numbers: true
};
msg.payload = generator.generate(options);
node.send(msg);
`

Or, better way than injecting a JSON string in "option" would be to add each property in the config node and use them to create an internal option object.  It is very unlikely that a flow would inject different pssoword options.

**Comment by naimo84** [comment]
Hey @pandosme ,


what's the error message you're getting, when you pass a JSON?
Unfortunately I've less time to "rewrite" the injectiong JSON String logic, right now...


So I tried to parse the JSON correctly with v0.1.0. It's already on the way.

Greets,
Benjamin

**Comment by pandosme** [comment]
I seem to use the Node in such a way that triggers your code make a JSON-parse on a javascript object.  See the example I showed.  I have found an alternative solution and is currently not using your Node.

 

/Fred 

 

Från: Benjamin ***@***.***> 
Skickat: den 6 juli 2022 08:21
Till: naimo84/node-red-contrib-generate-password ***@***.***>
Kopia: Pandos Me ***@***.***>; Mention ***@***.***>
Ämne: Re: [naimo84/node-red-contrib-generate-password] [BUG]: Cannot get enything to work (Issue #1)

 

Hey @pandosme <https://github.com/pandosme>  ,

what's the error message you're getting, when you pass a JSON?
Unfortunately I've less time to "rewrite" the injectiong JSON String logic, right now...

So I tried to parse the JSON correctly with v0.1.0. It's already on the way.

Greets,
Benjamin
